//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _671Books
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int cid { get; set; }
        public int bid { get; set; }
        public decimal price { get; set; }
        public string title { get; set; }
        public int edition { get; set; }
        public int year { get; set; }
        public string author { get; set; }
        public string publisher { get; set; }
        public string genre { get; set; }
        public bool inWishList { get; set; }
        public string orderStatus { get; set; }
        public int qtyinstore { get; set; }
    
        public virtual book book { get; set; }
        public virtual person person { get; set; }
    }
}
