//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _671Books
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderid { get; set; }
        public System.DateTime orderdate { get; set; }
        public decimal totalprice { get; set; }
        public string shippingaddress { get; set; }
        public string Status { get; set; }
        public int qtysold { get; set; }
        public int bid { get; set; }
        public int cid { get; set; }
    
        public virtual person person { get; set; }
        public virtual book book { get; set; }
    }
}
