//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _671Books
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public person()
        {
            this.Orders = new HashSet<Order>();
            this.Carts = new HashSet<Cart>();
        }
    
        public int cid { get; set; }
        public string name { get; set; }
        public long phone { get; set; }
        public string address { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string admin_status { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Cart> Carts { get; set; }
    }
}
